In [629]:
import warnings
import random
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, r2_score, f1_score, classification_report
from sklearn import preprocessing

In [630]:
def new_column_names(df_copy):
    column_list = ['label']
    row, column = 1,1;
    while row < 29:
        while column < 29:
            column_name = str(row) + 'x' + str(column)
            column_list.append(column_name)
            column+=1
        row+=1;
        if(column == 29):
            column = 1
            
    df_copy.columns = column_list
    return df_copy

def split_dataset_to_train_test_validation(df_copy, train_sze, test_sze, validation_sze):
    random.seed(0)
    target_column = ['label']
    predictors = list(set(list(df.columns))-set(target_column))
    X = df_copy[predictors].values #Contains all columns
    Y = df_copy[['label']].values
    X_train, X_temp, Y_train, Y_temp = train_test_split(X, Y, train_size=train_sze, random_state=50)
    X_test, X_validation, Y_test, Y_validation = train_test_split(X_temp, Y_temp, train_size=test_sze/(test_sze+validation_sze), random_state=50)
    return X_train, Y_train, X_test, Y_test, X_validation, Y_validation

In [631]:
warnings.filterwarnings('ignore')
df_train = pd.read_csv('MNIST_TRAIN.csv')
df_test = pd.read_csv('MNIST_TEST.csv')

In [632]:
print(df_train.isnull().sum().sum()); print(df_test.isnull().sum().sum())

0
0


In [633]:
X_train = df_train.drop('label', axis = 1)
X_test = df_test.drop('label', axis = 1)
print(X_train); print(X_test);

print('---------------------------------------------------------------')

Y_train = df_train[['label']]
Y_test = df_test[['label']]
print(Y_train); print(Y_test);

       1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  1x10  ...  28x19  28x20  \
0        0    0    0    0    0    0    0    0    0     0  ...      0      0   
1        0    0    0    0    0    0    0    0    0     0  ...      0      0   
2        0    0    0    0    0    0    0    0    0     0  ...      0      0   
3        0    0    0    0    0    0    0    0    0     0  ...      0      0   
4        0    0    0    0    0    0    0    0    0     0  ...      0      0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...    ...    ...   
59995    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59996    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59997    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59998    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59999    0    0    0    0    0    0    0    0    0     0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28

In [634]:
min_max_scaler = preprocessing.MinMaxScaler()
X_train = min_max_scaler.fit_transform(X_train)
X_test = min_max_scaler.fit_transform(X_test)

In [635]:
mlp = MLPClassifier(hidden_layer_sizes=(784,64,32,16,10), activation='relu', solver='adam', batch_size=16, max_iter=3, verbose=True)

In [636]:
mlp.fit(X_train, Y_train)

Iteration 1, loss = 0.30188836
Iteration 2, loss = 0.11441309
Iteration 3, loss = 0.08748982


MLPClassifier(batch_size=16, hidden_layer_sizes=(784, 64, 32, 16, 10),
              max_iter=3, verbose=True)

In [637]:
predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [638]:
print('Confusion Matrix of Train Set:'); print(confusion_matrix(Y_train, predict_train))
print('Classification Report of Train Set:'); print(classification_report(Y_train, predict_train))

print('------------------------------------------')

print('Confusion Matrix of Test Set:'); print(confusion_matrix(Y_test, predict_test))
print('Classification Report of Test Set:'); print(classification_report(Y_test, predict_test))

Confusion Matrix of Train Set:
[[5878    0    5    1    0    0   25    1   11    2]
 [   0 6709    7    4    3    0    5    6    7    1]
 [  13    8 5885   14    9    0    0   13   13    3]
 [   2    4   36 6043    0   14    0    7   17    8]
 [   3    1    2    0 5766    1   13    3    5   48]
 [  10    1    1   69    1 5287   33    0   17    2]
 [   5    0    1    0    3    5 5899    0    5    0]
 [   7   14   19   12    5    4    3 6146    6   49]
 [   2   17   14   17    0   14   19    2 5752   14]
 [  10    3    1   73   16   26    0   19   11 5790]]
Classification Report of Train Set:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5923
           1       0.99      1.00      0.99      6742
           2       0.99      0.99      0.99      5958
           3       0.97      0.99      0.98      6131
           4       0.99      0.99      0.99      5842
           5       0.99      0.98      0.98      5421
           6       0.98

In [639]:
print('Score of the train set: '); print(mlp.score(X_train, Y_train))
print('Score of the test set: '); print(mlp.score(X_test, Y_test))

Score of the train set: 
0.9859166666666667
Score of the test set: 
0.9759
