In [587]:
import warnings
import random
import pandas as pd
import numpy as np
from sklearn.neural_network import MLPClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score, confusion_matrix, r2_score, f1_score, classification_report
from sklearn import preprocessing

In [588]:
def new_column_names(df_copy):
    column_list = ['label']
    row, column = 1,1;
    while row < 29:
        while column < 29:
            column_name = str(row) + 'x' + str(column)
            column_list.append(column_name)
            column+=1
        row+=1;
        if(column == 29):
            column = 1
            
    df_copy.columns = column_list
    return df_copy

def split_dataset_to_train_test_validation(df_copy, train_sze, test_sze, validation_sze):
    random.seed(0)
    target_column = ['label']
    predictors = list(set(list(df.columns))-set(target_column))
    X = df_copy[predictors].values #Contains all columns
    Y = df_copy[['label']].values
    X_train, X_temp, Y_train, Y_temp = train_test_split(X, Y, train_size=train_sze, random_state=50)
    X_test, X_validation, Y_test, Y_validation = train_test_split(X_temp, Y_temp, train_size=test_sze/(test_sze+validation_sze), random_state=50)
    return X_train, Y_train, X_test, Y_test, X_validation, Y_validation

In [589]:
warnings.filterwarnings('ignore')
df_train = pd.read_csv('MNIST_TRAIN.csv')
df_test = pd.read_csv('MNIST_TEST.csv')

In [590]:
print(df_train.isnull().sum().sum()); print(df_test.isnull().sum().sum())

0
0


In [591]:
X_train = df_train.drop('label', axis = 1)
X_test = df_test.drop('label', axis = 1)
print(X_train); print(X_test);

print('---------------------------------------------------------------')

Y_train = df_train[['label']]
Y_test = df_test[['label']]
print(Y_train); print(Y_test);

       1x1  1x2  1x3  1x4  1x5  1x6  1x7  1x8  1x9  1x10  ...  28x19  28x20  \
0        0    0    0    0    0    0    0    0    0     0  ...      0      0   
1        0    0    0    0    0    0    0    0    0     0  ...      0      0   
2        0    0    0    0    0    0    0    0    0     0  ...      0      0   
3        0    0    0    0    0    0    0    0    0     0  ...      0      0   
4        0    0    0    0    0    0    0    0    0     0  ...      0      0   
...    ...  ...  ...  ...  ...  ...  ...  ...  ...   ...  ...    ...    ...   
59995    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59996    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59997    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59998    0    0    0    0    0    0    0    0    0     0  ...      0      0   
59999    0    0    0    0    0    0    0    0    0     0  ...      0      0   

       28x21  28x22  28x23  28x24  28x25  28x26  28

In [592]:
min_max_scaler = preprocessing.MinMaxScaler()
X_train = min_max_scaler.fit_transform(X_train)
X_test = min_max_scaler.fit_transform(X_test)

In [598]:
mlp = MLPClassifier(hidden_layer_sizes=(784,15,15,10), activation='relu', solver='adam', batch_size=16, max_iter=3, verbose=True)

In [599]:
mlp.fit(X_train, Y_train)

Iteration 1, loss = 0.30221786
Iteration 2, loss = 0.11735696
Iteration 3, loss = 0.08801870


MLPClassifier(batch_size=16, hidden_layer_sizes=(784, 15, 15, 10), max_iter=3,
              verbose=True)

In [600]:
predict_train = mlp.predict(X_train)
predict_test = mlp.predict(X_test)

In [601]:
print('Confusion Matrix of Train Set:'); print(confusion_matrix(Y_train, predict_train))
print('Classification Report of Train Set:'); print(classification_report(Y_train, predict_train))

print('------------------------------------------')

print('Confusion Matrix of Test Set:'); print(confusion_matrix(Y_test, predict_test))
print('Classification Report of Test Set:'); print(classification_report(Y_test, predict_test))

Confusion Matrix of Train Set:
[[5858    0    9    1    4    2   25    6    6   12]
 [   0 6667   49    2    3    0    0   15    6    0]
 [   6    1 5909   10   14    0    2   11    4    1]
 [   0    2   50 6040    0    3    0    7   15   14]
 [   3    2    3    0 5807    0    4    6    1   16]
 [   4    1    1   63    0 5266   36    3   20   27]
 [  10    2    5    1    9    2 5885    0    3    1]
 [   1   10   30    3    5    0    0 6204    3    9]
 [   3   15   54   10    5    6   14    5 5731    8]
 [   4    2    1   13   53    2    0   45    9 5820]]
Classification Report of Train Set:
              precision    recall  f1-score   support

           0       0.99      0.99      0.99      5923
           1       0.99      0.99      0.99      6742
           2       0.97      0.99      0.98      5958
           3       0.98      0.99      0.98      6131
           4       0.98      0.99      0.99      5842
           5       1.00      0.97      0.98      5421
           6       0.99

In [602]:
print('Score of the train set: '); print(mlp.score(X_train, Y_train))
print('Score of the test set: '); print(mlp.score(X_test, Y_test))

Score of the train set: 
0.98645
Score of the test set: 
0.9752
